// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM3V4rJOYpkb2QPyaGx-a27HzkiHDUqcg',
    appId: '1:282593100352:web:541be1bd019c42f25cd5a5',
    messagingSenderId: '282593100352',
    projectId: 'app-da-poli-v2',
    authDomain: 'app-da-poli-v2.firebaseapp.com',
    storageBucket: 'app-da-poli-v2.firebasestorage.app',
    measurementId: 'G-6JTXDRKT45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrgb1MfbeVSX88p7huqAa8Y3VjjuESVq0',
    appId: '1:282593100352:android:8d5f12a3067a984f5cd5a5',
    messagingSenderId: '282593100352',
    projectId: 'app-da-poli-v2',
    storageBucket: 'app-da-poli-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK3v6MWwH2MvRLhStb1DhBe2mvNRn81hA',
    appId: '1:282593100352:ios:8975a103ef3782375cd5a5',
    messagingSenderId: '282593100352',
    projectId: 'app-da-poli-v2',
    storageBucket: 'app-da-poli-v2.firebasestorage.app',
    iosBundleId: 'com.example.appDaPoli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK3v6MWwH2MvRLhStb1DhBe2mvNRn81hA',
    appId: '1:282593100352:ios:8975a103ef3782375cd5a5',
    messagingSenderId: '282593100352',
    projectId: 'app-da-poli-v2',
    storageBucket: 'app-da-poli-v2.firebasestorage.app',
    iosBundleId: 'com.example.appDaPoli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM3V4rJOYpkb2QPyaGx-a27HzkiHDUqcg',
    appId: '1:282593100352:web:3d3830a4e79a9abd5cd5a5',
    messagingSenderId: '282593100352',
    projectId: 'app-da-poli-v2',
    authDomain: 'app-da-poli-v2.firebaseapp.com',
    storageBucket: 'app-da-poli-v2.firebasestorage.app',
    measurementId: 'G-F2410407PY',
  );
}
