// lib/firebase_options.dart

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfB3Kl2xyDPfuVil_oMBLN4ZbdAwT5f6M',
    appId: '1:652592245254:web:9db5743a7cf66bf0bd7187',
    messagingSenderId: '652592245254',
    projectId: 'project-gp-12b38',
    authDomain: 'project-gp-12b38.firebaseapp.com',
    storageBucket: 'project-gp-12b38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5obxpq0nAO7WAGSJYrMdKEAQHx5eGax0',
    appId: '1:652592245254:android:ca3f96a5237fe7c9bd7187',
    messagingSenderId: '652592245254',
    projectId: 'project-gp-12b38',
    storageBucket: 'project-gp-12b38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9gc-HYOn611uoJ-LtuPfiFezbLjzfqfE',
    appId: '1:652592245254:ios:7f7cd1fa601a9619bd7187',
    messagingSenderId: '652592245254',
    projectId: 'project-gp-12b38',
    storageBucket: 'project-gp-12b38.firebasestorage.app',
    iosBundleId: 'com.example.appDaPoli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9gc-HYOn611uoJ-LtuPfiFezbLjzfqfE',
    appId: '1:652592245254:ios:7f7cd1fa601a9619bd7187',
    messagingSenderId: '652592245254',
    projectId: 'project-gp-12b38',
    storageBucket: 'project-gp-12b38.firebasestorage.app',
    iosBundleId: 'com.example.appDaPoli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfB3Kl2xyDPfuVil_oMBLN4ZbdAwT5f6M',
    appId: '1:652592245254:web:25a9070f82cd6b98bd7187',
    messagingSenderId: '652592245254',
    projectId: 'project-gp-12b38',
    authDomain: 'project-gp-12b38.firebaseapp.com',
    storageBucket: 'project-gp-12b38.firebasestorage.app',
  );

}